name: Bug Report
description: Report Texture Glitches, Not Working Textures, Other Texture Errors
title: "Bug: "
labels: ["Bug"]
assignees:
  - Yoru-Kitsune
body:
  - type: textarea
    id: bug-desc
    attributes:
      label: Bug
      description: Please describe what happens in the bug with the texture name.
      placeholder: ex. Titainum conveyor animation is not in correct order.
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: Expectations
      description: What do you think it should look like or what we should change? (Optional)
      placeholder: ex. Swap the 4-3 and the 4-4 frame of the animation.
    validations:
      required: false
  - type: textarea
    id: screenrecs
    attributes:
      label: Screenshots or Screenrecordings
      description: Please attach screenshots or screenrecordings of the bug. (Please, do not write in this field)
    validations:
      required: true
  - type: dropdown
    id: platforms
    attributes:
      label: Platforms
      description: On what platforms do you know the bug happens?
      multiple: true
      options:
        - Android
        - iOS
        - Mac
        - Windows
        - Linux
    validations:
      required: true
  - type: dropdown
    id: release
    attributes:
      label: Mod Releases
      description: On what mod releases is the bug?
      multiple: true
      options:
        - v.1.0.0
        - v.1.0.1
        - v.1.1.0
        - v.1.2.0
        - v.1.2.1
        - v.1.2.2
        - v.1.3.0
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Submission
      description:  By submitting this form you agree to following point.
      options:
        - label: I have searched open and closed issues for the same bug and I have not found anything that looks the same.
          required: true
         
