name: Bug Report
description: Report Texture Glitches, Not Working Textures, Other Texture Errors
title: "Bug: "
labels: ["Bug"]
assignees:
  - Yoru-Kitsune
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug
      description: Please describe what happens in the bug with the texture name.
      placeholder: ex. Titainum conveyor animation is not in correct order.
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: Expectations
      description: What do you think it should look like or what we should change? (Optional)
      placeholder: ex. Swap the 4-3 and the 4-4 frame of the animation.
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
