name: Texture Request
description: Request a vanilla texture to be added to the mod
title: "Texture Request: "
labels: ["Request"]
assignees:
  - Yoru-Kitsune
body:
  - type: textarea
    id: textures
    attributes:
      label: Textures
      description: Please list all Textures that you want to be added. Please use checkboxes (use: "- [ ] *") and if you don't know the **exact** name, please use images as addition.
      placeholder: ex. Titanium conveyor, Stone, Darksand, Copper Wall
    validations:
      required: true
  - type: textarea
    id: concepts
    attributes:
      label: Concepts or Ideas
      description: You can attach textures or write ideas how it could look like. (Optional)
      placeholder: If we are adding your texture we will contact you on this issue, so please check at least every 2 days. We will talk about further details on discord, so please only commit if you are owning an discord account.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Submission
      description:  By submitting this form you agree to following point.
      options:
        - label: I have searched open issues for the same texture and I have not found anything that contains the textures mentioned above.
          required: true
